
title: "cmu_panoptic_alg"
kind: "coco"
vis_freq: 1000
vis_n_elements: 10

image_shape: [384, 384]

opt:
  criterion: "MSESmooth"
  mse_smooth_threshold: 400

  n_objects_per_epoch: 15000
  n_epochs: 9999

  batch_size: 8
  val_batch_size: 16

  lr: 0.00001

  scale_keypoints_3d: 1

model:
  name: "alg"
  init_weights: true # false means that the checkpoint specified below is not loaded and the train starts from random
#  checkpoint: "./learnable_triangulation/learnable-triangulation-pytorch-master/data/pretrained/downloaded_pretrained_human36_alg_epoch60.pth"
  checkpoint: "./learnable_triangulation/learnable-triangulation-pytorch-master/data/pretrained/downloaded/cmu_alg_no_conf/iter_best.pth"

  use_confidences: false
  heatmap_multiplier: 100.0
  heatmap_softmax: true

  backbone:
    name: "resnet152"
    style: "simple"

    init_weights: True
    checkpoint: "./pose_estimation_2d/res152_256x192_d256x3_adam_lr1e-3_model_best.pth"
    num_joints: 17
    num_layers: 152

dataset:
  kind: "cmu"


  train:
    cmu_panoptic_root: "./cmu-panoptic/"
    labels_path: "./cmu-panoptic/processed/cmu-panoptic-multiview-labels.npy"
    with_damaged_actions: true
    undistort_images: true

    scale_bbox: 1.0

    shuffle: true
    randomize_n_views: True
    min_n_views: 3
    max_n_views: 5
    num_workers: 3

    # For train: cameras 0,1,4,6,8-19, 23-29
    # For val: 2,3,5,7,22,30
    # Missing data: 20-22, 30 - missing mrcnn bbox.
    ignore_cameras: [2,3,5,7,20,21,22,30]

    # val: 2, 13 , 16, 18 - samsung val cams
#    ignore_cameras: [2,13,16,18,20,21,22,30]
#    choose_cameras:
#      - 0
#      - 3  # full-view
#      - 7  # full-view
#      - 10 # full-view
#      - 15
#      - 19 # full-view
#
#    ignore_cameras:
#      # faulty
#      - 22
#      - 23
#      - 26
#      - 25
#      - 29
#      -
    retain_every_n_frames: 20

  val:
    cmu_panoptic_root: "./cmu-panoptic/"
    labels_path: "./cmu-panoptic/processed/cmu-panoptic-multiview-labels.npy"
    with_damaged_actions: true
    undistort_images: true

    scale_bbox: 1.0

    shuffle: false
    randomize_n_views: false
    min_n_views: 6
    max_n_views: 6
    num_workers: 2

    retain_every_n_frames: 20

    # For train: cameras 0,1,4,6,8-19, 23-29
    # Missing data for val: 20-21 - missing mrcnn bbox.
    # For val: 2,3,5,7,22,30
    ignore_cameras: [0,1,4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29]

    # val: 2, 13 , 16, 18 - samsung val cams
#    ignore_cameras: [0,1,3,4,5,6,7,8,9,10,11,12,14,15,17,19,20,21,22,23,24,25,26,27,28,29,30]
#    choose_cameras:
#      - 2
#      - 5
#      - 13
#
#    # faulty
#    ignore_cameras:
#      - 23
#      - 26
#      - 25
#      - 29