"""
 This file was copied from github.com/karfly/learnable-triangulation-pytorch and modified for this project needs.
 The license of the file is in: github.com/karfly/learnable-triangulation-pytorch/blob/master/LICENSE
"""
title: "human36m_vol_softmax"
kind: "human36m"
vis_freq: 1000
vis_n_elements: 10

image_shape: [384, 384]

opt:
  criterion: "MAE"

  use_volumetric_ce_loss: true
  volumetric_ce_loss_weight: 0.01

  n_objects_per_epoch: 15000
  n_epochs: 9999

  batch_size: 5
  val_batch_size: 10

  lr: 0.0001
  process_features_lr: 0.001
  volume_net_lr: 0.001

  scale_keypoints_3d: 1

model:
  name: "vol"
  kind: "mpii"
  volume_aggregation_method: "softmax"

  init_weights: false
  checkpoint: ""

  use_gt_pelvis: false

  cuboid_side: 250.0

  volume_size: 64
  volume_multiplier: 1.0
  volume_softmax: true

  heatmap_softmax: true
  heatmap_multiplier: 100.0

  backbone:
    name: "resnet152"
    style: "simple"

    init_weights: true
#    checkpoint: "./pose_resnet_4.5_pixels_human36m.pth"
    checkpoint: "./deep-high-resolution-net.pytorch-master/output/coco/pose_resnet/res152_256x192_d256x3_adam_lr1e-3/model_best.pth"

    num_joints: 17
    num_layers: 152

dataset:
  kind: "human36m"

  train:
    h36m_root: "./data/human36m/processed/"
    labels_path: "./data/human36m/extra/human36m-multiview-labels-GTbboxes.npy"
    pred_results_path: "./data/pretrained/human36m/human36m_alg_10-04-2019/checkpoints/0060/results/train.pkl"

    with_damaged_actions: true
    undistort_images: true

    scale_bbox: 1.0

    shuffle: true
    randomize_n_views: false
    min_n_views: null
    max_n_views: null
    num_workers: 5

  val:
    h36m_root: "./data/human36m/processed/"
    labels_path: "./data/human36m/extra/human36m-multiview-labels-GTbboxes.npy"
    pred_results_path: "./data/pretrained/human36m/human36m_alg_10-04-2019/checkpoints/0060/results/val.pkl"

    with_damaged_actions: true
    undistort_images: true

    scale_bbox: 1.0

    shuffle: false
    randomize_n_views: false
    min_n_views: null
    max_n_views: null
    num_workers: 10

    retain_every_n_frames_in_test: 1
